# Site settings
title: growltiger
email: your-email@domain.com
url: http://www.growltiger23.com
description: "Growltiger was a Bravo Cat, who lived upon a barge,In fact he was the roughest cat that ever roamed at large. From Gravesend up to Oxford he pursued his evil aims, Rejoicing in his title of The Terror of the Thames."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Build settings
markdown: kramdown
permalink: pretty
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
